### ISSUE TITLE
Decoding Issue

### ISSUE THREAD

**Issue by PG-TUe** [openml/python#19]
I run into a decoding issue when trying to retrieve information about the dataset, when running the code
````
from openml.apiconnector import APIConnector
connector = APIConnector(apikey = 'key')
task = connector.download_task(59)
dataset = task.get_dataset()
X, y, categorical = dataset.get_dataset(target=dataset.default_target_attribute)
````
I get 
````
Traceback (most recent call last):
  File "...\OpenML\TaskScript.py", line 15, in <module>
    X, y, categorical = dataset.get_dataset(target=dataset.default_target_attribute)
  File "...\OpenML\openml\entities\dataset.py", line 138, in get_dataset
    data, categorical, attribute_names = pickle.load(fh)
  File "...\python-3.4.3.amd64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 977: character maps to <undefined>
````
If it helps, I'm using Python3.4.3 and my default encoding is utf-8 (sys.getdefaultencoding()), though the traceback suggests cp1252 was used.

**Comment by zardaloop** [comment]
What exactly you are trying to do here?

**Comment by joaquinvanschoren** [comment]
Hmm, this is indeed confusing, you are effectively doing:
task.get_dataset().get_dataset(target=dataset.default_target_attribute)

Why the double get_dataset()?

Cheers,
Joaquin

**Comment by zardaloop** [comment]
If I wanted to do this I would write something like this in first place: 

```python
from openml.apiconnector import APIConnector
import os

workdir = os.path.dirname(os.path.abspath(__file__))
workdir = os.path.join(workdir, "tmp")
connector = APIConnector(cache_directory=workdir)
connector = APIConnector(cache_directory=workdir, apikey='Your_API_Goes_Here')
task = connector.download_task(59)
dataset = connector.download_dataset(task.dataset_id)
file = dataset.data_file
#or if you only need the url
file_url = dataset.url
```
However if you are trying to do more with the data like running algorithem stuff then you need some other libraries like the ones are mentioned here https://weka.wikispaces.com/Can+I+use+WEKA+from+Python%3F

**Comment by PG-TUe** [comment]
I guess I'm slightly confused then, but doesn't task.get_dataset() return a Dataset Entity whereas dataset.get_dataset(target=dataset.default_target_attribute) returns the actual data in two variables: X (non-target attributes) and y (target attributes)?

My goal was to retrieve the attributes to learn from (X) and their labels (y), so that I can then apply some (scikit) machine learning algorithm on them. Which ends up in something like
````
from sklearn import preprocessing, ensemble
from openml.apiconnector import APIConnector

connector = APIConnector(apikey = 'API-key')
task = connector.download_task(59)
dataset = task.get_dataset()
train,test = task.get_train_test_split_indices()
X, y = dataset.get_dataset(target=dataset.default_target_attribute)
clf = ensemble.RandomForestClassifier()
clf.fit(X[train], y[train])
pred_y = clf.predict_proba(X[test])
````
I would do this directly through task.get_train_and_test_set(), but that method calls self.get_X_and_Y() which calls dataset.get_pandas(target=self.target_feature), and get_pandas isn't a function of dataset (see my other issue).

**Comment by joaquinvanschoren** [comment]
Hmm, I'm also a bit confused. The following should work right (I think it used to)? I want to use scikit-learn here:
```
from openml.apiconnector import APIConnector
from sklearn import preprocessing, ensemble
import os

work_dir = os.path.dirname(os.path.abspath("__file__"))
work_dir = os.path.join(work_dir, "tmp")
connector = APIConnector(cache_directory=work_dir, apikey='4156a6bdd8477568ec6dcd701051c91d')
task = connector.download_task(59)
dataset = connector.download_dataset(task.dataset_id)
X, y, categorical = dataset.get_pandas(target=dataset.default_target_attribute)
clf = ensemble.RandomForestClassifier()
clf.fit(X, y)
```

Only I get the following error. Is the get_pandas() method removed?
```
WARNING:openml.apiconnector:Data from http://www.openml.org/data/download/61/dataset_61_iris.arff has content type application/octet-stream; going to treat this as ascii.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-ba720a152af5> in <module>()
      8 task = connector.download_task(59)
      9 dataset = connector.download_dataset(task.dataset_id)
---> 10 X, y, categorical = dataset.get_pandas(target=dataset.default_target_attribute)
     11 clf = ensemble.RandomForestClassifier()
     12 clf.fit(X, y)

AttributeError: 'OpenMLDataset' object has no attribute 'get_pandas'
```

**Comment by zardaloop** [comment]
I can't test it just now because I don't have my laptop with me, but I guess what you need is  get_X_and_Y().

Have a look at here(https://github.com/openml/python/blob/master/openml/entities/task.py)  from line 44 to 48. @mfeurer  should know more about. 

I hope that helps. :)

Cheers

**Comment by joaquinvanschoren** [comment]
Thanks, but if I try that it returns an error:
```
task = connector.download_task(59)
X, y, categorical = task.get_X_and_Y()
---
AttributeError: 'OpenMLDataset' object has no attribute 'get_pandas'
```

**Comment by PG-TUe** [comment]
Yes. That's an observation I made too. It seems that get_pandas has been replaced by (or renamed to) get_dataset. So when you call get_X_and_Y(), which also calls get_pandas (see line 47 of task.py), you get an error as well.

**Comment by joaquinvanschoren** [comment]
Ok, I figured it out. There is a bug in entities/task.py:
line 47 should be: 
```
X_and_Y = dataset.get_dataset(target=self.target_feature)
```
instead of:
```
X_and_Y = dataset.get_pandas(target=self.target_feature)
```

This example works fine:
```
from openml.apiconnector import APIConnector
from sklearn import preprocessing, ensemble
import os

work_dir = os.path.dirname(os.path.abspath("__file__"))
work_dir = os.path.join(work_dir, "tmp")
connector = APIConnector(cache_directory=work_dir, apikey='xxx')
task = connector.download_task(59)
dataset = connector.download_dataset(task.dataset_id)
X, y = dataset.get_dataset(target=dataset.default_target_attribute)
clf = ensemble.RandomForestClassifier()
clf.fit(X, y)
```

**Comment by joaquinvanschoren** [comment]
I committed a bugfix. All the relevant tests have passed.

**Comment by joaquinvanschoren** [comment]
This also works now. @PG-TUe please close if this resolves your issue
```
from openml.apiconnector import APIConnector
from sklearn import preprocessing, ensemble
import os

work_dir = os.path.dirname(os.path.abspath("__file__"))
work_dir = os.path.join(work_dir, "tmp")
connector = APIConnector(cache_directory=work_dir, apikey='xxx')
task = connector.download_task(59)
X, y = task.get_X_and_Y()
clf = ensemble.RandomForestClassifier()
clf.fit(X, y)
```

**Comment by zardaloop** [comment]
That's great... problem solved :) 

Could you also please merge the same commit into develop branch. 
Also you need to label the commits folowing the gitflow pattern. http://nvie.com/posts/a-successful-git-branching-model/#hotfix-branches

**Comment by PG-TUe** [comment]
Yup. That is what I described in [this issue](https://github.com/openml/python/issues/18). 
However, having done that, I get the decoding error that I described in this issue. Which version of python are you using? And which OS?
I'm using Python 3.4.3 on Windows, and eventhough the [default encoding should be utf-8](https://docs.python.org/3.4/howto/unicode.html), for me it seems to use CP1252, which causes a problem.
For you, it probably does use UTF-8.
I tried to modify line 137 of dataset.py from 
````
 with open(path) as fh:
````
to
````
 with open(path, encoding="utf8") as fh:
````
to simply see if that helped, but I have some issues re-installing the newly built module, and not enough time to fix it and see what the results are today.

**Comment by joaquinvanschoren** [comment]
OK. I'm running Python 2.7.9 on Linux.

**Comment by joaquinvanschoren** [comment]
Ah, this is fixed in a hotfix branch but not yet pulled to master.
https://github.com/openml/python/compare/hotfix/fixtests

You need to replace that line with:
```
with open(path, "rb") as fh:
```

@mfeurer What should we do about this? Do you want to pull the hotfix into master and develop?

**Comment by joaquinvanschoren** [comment]
@PG-TUe The hotfix has now been pulled into master by @zardaloop. Can you try again?

**Comment by PG-TUe** [comment]
The hotfixed solved the issue. Thanks for the help.
