### ISSUE TITLE
Absolute Path required when uploading run

### ISSUE THREAD

**Issue by PG-TUe** [openml/python#31]
When uploading a run (and probably other openml objects as well), you need to provide files, such as a run description, or a predictions file. Upload_run currently requires an absolute path to the files (this is also true in the feature/Upload_Fixes branch). This is caused by the following line ([from here](https://github.com/openml/python/blob/feature/Upload_Fixes/openml/apiconnector.py#L861))
```
if os.path.isabs(path) and os.path.exists(path):
    do-file-things
```
to me, it would make sense to change that to:
```
if not os.path.isabs(path):
    path = os.path.abspath(path)
if (os.path.exists(path)):
    do-file-things
```
So it would accept both absolute and relative paths. Is there a particular reason this wasn't done?

**Comment by joaquinvanschoren** [comment]
Not that I know of. Go ahead and do that :)

**Comment by zardaloop** [comment]
What's the difference? you need to have an absolute path anyway in first place? Why anyone would ever want to pass a relative path? It is not the responsibility of the api to convert a relative oath to absolute path. I think it is fine the way it is.

**Comment by zardaloop** [comment]
Api I mean the plugin

**Comment by joaquinvanschoren** [comment]
Ah, good point.
@PG-TUe, can you make openml_run return absolute paths instead?

**Comment by PG-TUe** [comment]
Whenever I generate files in my projects, I tend to write it to a relative path, for example a folder called 'output' in the folder where I run the script. This makes it easier whenever I want to run the script on another computer, or in a different location on the same computer. So in the case of openml_run, I generate the file under a relative path as well, which means that in order to pass it to the API, I have to retrieve the absolute path specifically to interact with the API.

Of course it is only a line of code - but it is a line of code that everyone interacting with the API will have to include in their scripts (if you don't already work with absolute paths), and have to be aware of. Otherwise they just get notified that their file does not exist.

**Comment by zardaloop** [comment]
ok granted what you are saying and I agree. So go ahead and do it this way. 

```python
path = os.path.abspath(path)
if os.path.exists(path):
    do-file-things
```

You don't need to check if it is absolute path or not, just go ahead and convert it to one and then check if it exists.

**Comment by PG-TUe** [comment]
I'm closing this issue it is resolved per [this merge](https://github.com/openml/python/pull/37#event-557431029).
