### ISSUE TITLE
openml_run broken?

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/python#36]
This does not work anymore. It requires a get_train_and_test_set() in Task but it does not exist.
It was working a few days ago?

--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-afb9c1f81934> in <module>()
      2 
      3 clf = ensemble.RandomForestClassifier()
----> 4 prediction_path, description_path = openml_run(task, clf)
      5 print("RandomForest has run on the task.")
      6 print("Predictions stored: %s" % prediction_path)

/Users/joa/anaconda/lib/python3.5/site-packages/openml-0.2.1-py3.5.egg/openml/autorun.py in openml_run(task, classifier)
    197         for f in range(0, nr_folds):
    198             start_time = time.time()
--> 199             TrainX, TrainY, TestX, TestY = task.get_train_and_test_set(f, r)
    200             _,test_idx = task.get_train_test_split_indices(f)
    201 

AttributeError: 'OpenMLTask' object has no attribute 'get_train_and_test_set'

**Comment by PG-TUe** [comment]
I'll look into it. It probably has to do with the change from the other branch iterate-of-tasks (or something like it), which allowed for a way to get information about the splits from the task. I thought it only added a new way to access it, but I suppose maybe it also invalidated the old way.

**Comment by joaquinvanschoren** [comment]
Yes, Matthias' update replaced that function, so openml_run likely needs to
be updated...

**Comment by PG-TUe** [comment]
I'll change it in a hotfix branch.

**Comment by joaquinvanschoren** [comment]
thanks!

**Comment by PG-TUe** [comment]
Do you think it is fine if I also do the small changes proposed in [issue 31](https://github.com/openml/python/issues/31) in this hotfix? Shouldn't really impact anything.

**Comment by joaquinvanschoren** [comment]
yes please :)

**Comment by PG-TUe** [comment]
I was able to reproduce your issue running the `examples\sklearn` folder\openml_run_example.py`, I reworked the openml_run script to work with the new way of accessing the splits.  Please look at [this branch](https://github.com/openml/python/tree/hotfix/Issue31_36) to see if it fixed your issue.

The branch also implemented the change suggested for Issue 31.

**Comment by PG-TUe** [comment]
I'm closing this issue as they should be resolved per [this merge](https://github.com/openml/python/pull/37#event-557431029).
