### ISSUE TITLE
Do not crash if the authentication is lost

### ISSUE THREAD

**Issue by mfeurer** [openml/python#6]
Re-authenticate in that case. To do this, implement authenticate.check, and re-authenticate if necessary.

**Comment by joaquinvanschoren** [comment]
Does this still happen? I believe that the session keys are now of unlimited length, as we are moving from session keys to API keys. 

In any case, re-authenticating when the authentication is lost is a good idea anyway.

**Comment by mfeurer** [comment]
I didn't try it lately. Since I implemented a proper cache, I barely have to download anything anymore.

**Comment by joaquinvanschoren** [comment]
This can be closed now? We use API keys now that do not expire.

**Comment by mfeurer** [comment]
Yes.
